# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: global_api_development

test:
  <<: *default
  database: global_api_test

production:
  <<: *default
  database: global_api_production
